dist: trusty
language: scala
scala:
  - 2.11.11
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
before_deploy: "sbt ++$TRAVIS_SCALA_VERSION clean dist"
deploy:
  provider: releases
  api_key:
    secure: MijebRlWdyRf5oHgKkZ1Iv+afGwZaSWc0r/rcLK5GxuFawtghNumQS84mdr9No3LYR+2HsXCFfxivOWzMNoOb1pgPlh5sS99EazLW9smRkcPNy1TXBMzMOOxk8U5W1jQbfx2rZngdlT487KJuruvjl10srqAgAWlC2Znyo7jpXyuDUtWSBpBwuVVInIsbnwUl0vhavng0rISmSQIrDUWBTs/DFdhfVQVbzLXxPfN/2V2VpDU9KfR7ePK4AQBCyYtk+83rwiZFk0tMWNC4X0p3LLHhd8HzpYssDJJNQbl3vOzyU9X78ydYSRljrMOI3REPBWKumsn76UqnZzVKarpG7DuX5MYXiI3fbYX4QGzn9p4nEXRK+nJpOAf/he3bsh0TvgodaPLa1+WHtMzyn6mxQqh4FleSN+2knlASMVyvxVGzMaR4z8lTUGhSDJs0pk3353AYSZ3G1yLDnzOjlpIXkBJQfclEGY7C2a7F5WcgjnkQuTPsJCdmGtOsRtC8miK8kEuVmyVBwBbH2p1ItSuhGFjADeZ06hfkFHwozRA9fJBHcdCVggbkiqObFBZVxZt8NqTyyiZ34c5jHLMmdI0gueUjPJQr+S+xb8a7J5x1zyN5/hBFioVcXENiky7Ymd+vtlc7MRCkX6xVz9Zrg0oJMxTWZepnXUe8mIgv05Og1g=
  file: "target/universal/rights-app-dist.zip"
  skip_cleanup: true
  on:
    tags: true
