language: scala
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
before_deploy: "sbt ++$TRAVIS_SCALA_VERSION clean dist"
deploy:
  provider: releases
  api_key:
    secure: T/z45lTYnT70tSvLib5OXaFLdKUYrgsGcraWkNSbdcNp0lHcm/6Zr6YF/C+mMH0Uu9617HelPK4RMBIXjeZlasSVnqwqrwfoVOh0fcxEn2aXGkFh4BOK43xoq9jk1aylwPM7F2KCq06mWrSv6Bq6GmfCHAZZ51fTvBZ9PmOX133hCo1g9JdfzdMt7HWrv+IHoCmsTH1PLm4Zg726uU5yEivc1TaK8tLJ1bGzg7f4GneZi2e/BKjZ95N8G6X24joCRnf38d6u55b9m/adeClVmdd3FRv4l62bJFqbS+NVFowik5hj8UEOcAxc7z6/fpbDKzHCsxTFesdiVY1QTyOnLisde1ejF44u+6Xb+I/v0vT1gPJsxh0gRGpGNCuc4ULbzM7L6kAZP4ecCQahoWCRZgehjpW+XBhctys5UpISjzDT6ciHzxC7weD5ZBupNZeV80FS/bTjCh/6QmuM80+6UgJ7it8CRDD5LJvovYLzAHNmn9rp3pDZ01Fgx3K9jTgDr48ZO/SiI+nV7MRyLDl/tX624M7pEX4o+RLtB5kfD1JJb97AQ64/WQDR54IDj/igyhTjKpXDvxicGodjGYK87lJge3Ml1EwE2hx9S8WSt1k/HC4hIItvZp9/qL9/vGL9TEFWYLc498Lu+IZsf53Zg0IhJGGcnWjvwFVADnsOfow=
  file: "target/universal/rights-app-dist.zip"
  skip_cleanup: true
  on:
    tags: true
