language: scala
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
before_deploy: "sbt ++$TRAVIS_SCALA_VERSION clean dist"
deploy:
  provider: releases
  api-key:
    secure: mi8PRHV/jqGOdFss9XMpwy5JYKrKqrGTinkJUhzZqimileoEfSs5+6ALPY/nbM4hN+qGRHdIEFFoO4A4xZ25yl4E4xMUNsZvSGVx/w5boiEgBy/6M+5lKqIleWB+wQXLKEwNptiSrFRTqjSahN/zUv0P/WYMc8jBx8k/pSLyXtOEwIK4zcu83GrQVQJMgmY49ziFJwuXASZLeBszuPwpQyPP/iPHl1nRURo0T4O9wwqbrw4/Xf5E64IhkZKTW7w35SGq0Kstltzcv6q0Z1DrOrP94Gpttcbbsp1/dC+s4zLoC871Zh9Td1e0QhTJV/UEpteI53npw7+cDQzEEROeMR6LGekoGIAqssjcmFXrBfNgY6UyRevMb0+VwGif94K3fQFzJfKMTicDtsdwOF/jPiTcjIh6LtofkW0AHU203x52+RM7LEj9VwTeANl8b7og5llkB4DoC6pFBnKZksaRXERdadHIYUoIVr+7ZAu7tgeFn2Wwy3AsFeIg+2KOjPoBOsyFAEK88Yr5RQVEljrB5Kk6QhM0u1AqJVF4eE1Efu5l5XOfUXedNFb/U4Kf8SdpycGEkhnluVhoPvdpaXuUZ66viQSO+oLvldHOa9yEWIQ1cFr2Jv3rADBuyYrKH9kPMhcNuR1gTx79L8VdfwTgljmAx5mvTw0+0zW6UHgdsSg=
  file: "target/universal/rights-app-dist.zip"
  skip_cleanup: true
  on:
    tags: true
