apiVersion: apps/v1
kind: Deployment
metadata:
  name: rights-app-deployment
spec:
  template:
    spec:
      containers:
        - name: rights-app
          # required to use local image
          imagePullPolicy: Never